const router = require("express").Router()
const dashboardController = require("../../controllers/admin/dashboard.controller")
const lessonRouter = require("./lesson.route")
const homeRouter = require("./home.route")
const studyRouter = require("./study.route")
router.get("/",dashboardController.page)
router.use("/lesson",lessonRouter)
router.use("/home",homeRouter)
router.use("/study",studyRouter)
module.exports = router